### ISSUE TITLE
Proposal: package.toml format

### ISSUE THREAD

**Issue by jromero** [buildpack/pack#376]
This toml format is proposed based on understandings from [RFC-7](https://github.com/buildpack/rfcs/blob/master/text/0007-spec-distribution.md#buildpack-developer) and [distribution spec](https://github.com/buildpack/spec/blob/master/distribution.md#buildpackage).

```toml
# The buildpack source intended for packaging
[buildpack]
uri = "."

# ... as an archive
[buildpack]
uri = "http://.../bp.tgz"

# Additional buildpacks which this buildpack depends on. [optional]
# ... as an image
[[dependencies]]
image = "myrepo.org/some/image"

# ... as an archive (cnb)
[[dependencies]]
uri = "http://artifacts.store/some/image.cnb"

# ... as a local file archive (tgz)
[[dependencies]]
uri = "file:///some/bp.tgz"
```

### Future Planning

* URI schema for docker (cnb) images (RFC needed)
* Create a table for additional information, for example:
```
# ... as a git resource (future planning)
[buildpack.git]
reference = "master"

# ... as an s3 resource (future planning)
[buildpack.s3]
bucket = "bp-bucket"
region = "us-east-1"

# ... as a git resource (future planning)
[[dependencies]]
[dependencies.git]
reference = "master"

# ... as an s3 resource (future planning)
[[dependencies]]
[dependencies.s3]
bucket = "bp-bucket"
region = "us-east-1"
```

## FAQs

- What about stacks?
    - Stacks are computed based on the "intersection" of all stacks provided by the `buildpack` and it's `dependencies`.
<hr />

_NOTE: This description is a living document until proposal is approved and implemented. It will be updated as conversation are had._

**Comment by jromero** [comment]
@ecasey and I have updated the format based on some lengthy discussions with various individuals.

A few notes:

1. We focused on trying to make it easy to understand while still flexible enough for future additions.
1. We opted to set forth a proposal to group related keys under a separate object to hopefully make it easier to perceive (and document) a group of keys as "resources" to configure _how_ to retrieve source.
1. We are punting on explicitly restricting `stacks` until further requests and use cases make it more apparent that it's necessary. At the moment we will compute the compatible stacks. **See FAQ**. Open to further discussions if necessary.
1. Naming is hard. We arrived at `dependencies` as the less confusing, more explicit term to use but open to alternative suggestions. Prior suggestions that didn't quite work: `buildpacks` (plural), `additional-buildpacks`, `sources`. 

As always, eager to hear feedback.

**Comment by matthewmcnew** [comment]
Do `dependencies` need to actually be a dependency of the buildpack?

**Comment by jromero** [comment]
> Do `dependencies` need to actually be a dependency of the buildpack?

The intention is certainly for them to be dependencies. 

Are you thinking about a similar case to that of `builder` in which you can package an arbitrary number of buildpacks together?

**Comment by matthewmcnew** [comment]
Similar, yes. Previously, when the `package.toml` had a `default` it implied that it could package alternative sets of buildpacks.

**Comment by jromero** [comment]
That's partly the reason for the rename. @sclevine could probably elaborate a little more on this but I think we are trying to drive home the understanding that:

A _packaged buildpack_ (and it's dependencies) **_is_** a buildpack. In other-words, a [buildpackage](https://github.com/buildpack/spec/blob/master/distribution.md#buildpackage) is just the format of how a buildpack is packaged.

**Comment by jkutner** [comment]
When using `[buildpack.git]` is the `[buildpack] uri` ignored? I don't understand how these do or do not work together. For example, let's say I have:

```toml
[buildpack]
uri = "http://.../bp.tgz"

[buildpack.git]
repo = "git.repo/..."
reference = "master"
```

Is this an invalid `package.toml`?

**Comment by jromero** [comment]
@jkutner They don't work together. In the provided example they are only their to exhastively show different permutations of `[buildpack]`.

To your concern about providing multiple resource types, the same could be said if someone provides an `[buildpack] image` and `[buildpack] uri`.

```
[buildpack]
uri = "."
image = "some/image"
```
Failing as _invalid_ is one way we could handle it. Another option could be setting an order of precedence such as:

> Order of precedence:
> - uri
> - image
> - git
> - s3
> - ...

I lean towards the robustness of an order of precedence but don't have too strong of an opinion.

**Comment by jkutner** [comment]
what about using well defined URI schemes:

```
[buildpack]
uri = "git://..." # we could establish a pattern for referencing a branch like `...#master`

[buildpack]
uri = "s3://..." # this would contain the region and bucket in the URI
```

Another option could be:

```
[buildpack]
type = "<git,http,s3>"
```

I'm not even sure i like `type` better, but wanted to toss it in.

**Comment by jromero** [comment]
#### RE: URI schemes

It's hard for me to perceive the idea that we could create a single line format for every "type" in the future without ultimately creating more confusion. For example the [`s3` schema](https://github.com/aws/aws-sdk-php/blob/master/tests/S3/S3UriParserTest.php) already exists and doesn't contain `region`. The same could be said for `git` but say you wanted to specify a public key as part of the config.

I like the idea in principle, just not sure how practical it would end up.

#### RE: Types

We did discuss this option and I would say there were no strong opinions either way. That said it wouldn't solve the original concern. For example,

```
[buildpack]
type = "uri"
uri = "."
image = "some/image"
```

Although it might make it more apparent and it would definitely be easier to parse. Downside is that single key elements then become at least two keys.

```
[buildpack]
type = "image"
image = "some/image"
```

VS

```
[buildpack]
type = "uri"
uri = "http://..."
```

**Comment by jkutner** [comment]
What if `[buildpack] uri` is always required and `[buildpack.xxx]` supplements it with type-specific fields? For example:

```toml
[buildpack]
uri = "s3://bucket-name/key"

[buildpack.s3]
region = "us-east-1"
```

or

```toml
[buildpack]
uri = "git://..."

[buildpack.git]
ref = "master"
```

In this way, we can probably support many different `uri` values/schemes without the `[buildpack.xxx]` in a lots of cases.
